### ISSUE TITLE
User Account Sign Up

### ISSUE THREAD

**Issue by CheesyGamer77** [COSC481W-2023Fall/Bookworm#3]
As a user, I want to be able to sign up for an account with the service. This would allow me to connect with other users of the service and save my preferences.

Tasks:
- [ ] Create an account database
- [ ] Setup API endpoints for account creation
- [ ] Create a UI for creating account

Acceptance Criteria:
- [ ] Pass applicable unit tests
- [ ] Users are able to create a new account through the page with a preferred username and password
- [ ] Users are shown an error if they attempt to sign up for an account that already shares the given username

**Comment by tfurey96** [comment]
Completed
