### ISSUE TITLE
Book View Enhancement in homepage

### ISSUE THREAD

**Issue by huan3846** [COSC481W-2023Fall/Bookworm#58]
# PBI: Book View Enhancement in homepage
## User Story
As a user, I want to view book information within bookshelf and recommendations on the homepage. When I click on a specific book, I expect to be redirected to the corresponding book view page for detailed information.

- Persona: A user who enjoys exploring and discovering books and values convenience
- Feature: Clicking on a specific book redirects the user to the corresponding book view page.
- Business Value: Providing users with easy access to detailed book information within the homepage.

## Tasks

- [x] Implement Click Event Handling
- [x] Retrieve and Display Book Information

## Acceptance Criteria

1. Upon clicking on a book in the bookshelves or recommendations, the user should be seamlessly redirected to the corresponding book view page.
2. The book view page should display detailed information about the selected book.

**Comment by CheesyGamer77** [comment]
Assignments for this PBI have changed due to a previous commit already addressing this PBI. Will close this when it's merged.

Refs: https://github.com/COSC481W-2023Fall/Bookworm/commit/5e20d1aafa91a3b6732b3cc46ae366c2ee7c8854
